### ISSUE TITLE
New release containing the filter on label

### ISSUE THREAD

**Issue by Stanislasss** [ryane/kfilt#11]
Hi,
It would be nice to be able to get the filtering based on label in released version.
We currently need to point to master and build it every time we want to fetch kfilt.
Could you create a release for it? And by the way the feature works great ;-)

Best,

**Comment by ryane** [comment]
Sorry for the delay - just released 0.0.4. Thanks!

**Comment by Stanislasss** [comment]
No worry and thanks for taking the time ;-)
