### ISSUE TITLE
Filter name based on regex ?

### ISSUE THREAD

**Issue by sgaunet** [ryane/kfilt#15]
Hi,

I'm using kfilt on a collection of manifests and in the kustomization.yaml, for some reason, I'm using the option nameSuffix. So when I want to filter, it can be tricky to think, ha yes, I need to search the resource named foo-nameSuffix. And for my colleagues, it should great to :

* search resource name with regex
* or filter should return ressources that have the name contained in it (pkg/filter/matcher.go line 33 : if s.Name != "" && !strings.Contains(r.GetName(),s.Name) { )

I understand that second option is not very beautiful...
If the project is strill alive, I'm open to discuss about this and eventually take in charge (but I'm not a good developper, I'm an ops ...)

**Comment by ryane** [comment]
Ah, yeah, that definitely would be a handy feature to have when using the `nameSuffix` transformer. I think I would prefer the first option too. If you want to take it on, please go for it. Otherwise, I'll see if I can find some time for it soon.

**Comment by ryane** [comment]
added wildcard support for names. Hopefully this is sufficient.

**Comment by sgaunet** [comment]
And it is, thanks a lot :) 
Happy new year.
