### ISSUE TITLE
Filters Should Not Re-arrange Kustomize Output

### ISSUE THREAD

**Issue by GuyPaddock** [ryane/kfilt#23]
It appears that when output from `kustomize` is piped into the Docker-based version of `kfilt` and multiple `kind` filters are in use, the order that resources appear in the output is controlled by the order that the filters appear on the command-line. Instead, the order of the resources from the `kustomize` output should be respected, since Kustomize outputs them in roughly dependency order. Otherwise, things like namespaces, secrets, or PVs sometimes end up not being created before the things that depend on them.

As a workaround, the user can ensure that they only specify filters in an order that matches how Kustomize would sort them.

**Comment by GuyPaddock** [comment]
Separately, @ryane I want to thank you for writing this tool. It is extremely helpful!

**Comment by ryane** [comment]
thanks @GuyPaddock! I see what you mean and I can repro it. I'll work on a fix.

**Comment by ryane** [comment]
latest release should fix this. good catch, thanks again!
